Vivanet-Org/testxpress

src/app/app.component.html
src/app/app.component.spec.ts
src/app/card/card.component.spec.ts
src/app/card/card.component.ts
src/app/mainproject/mainproject.component.spec.ts
src/app/test-express-top-nav/test-express-top-nav.component.spec.ts
src/app/test-express-top-nav/test-express-top-nav.component.ts
src/app/users.service.spec.ts
src/app/users.service.ts

APIs are updated and test cases are written

---

src/app/app.component.css
src/app/applications/applications.component.css
src/app/applications/applications.component.html
src/app/applications/applications.component.ts
src/app/card/card.component.html
src/app/card/card.component.ts
src/app/test-express-nav/test-express-nav.component.ts
src/app/users.service.ts
src/styles.css

I have updated the code for unit test cases.
Please review and merge

updated test cases

---

src/app/applications/applications.component.css
src/app/applications/applications.component.spec.ts
src/app/card/card.component.spec.ts
src/app/test-express-top-nav/test-express-top-nav.component.spec.ts
src/app/users.service.spec.ts

Updated test cases.
Please review and merge

Updated test cases.

---

package-lock.json
package.json
src/app/applications/applications.component.css
src/app/applications/applications.component.html
src/app/applications/applications.component.ts
src/app/card/card.component.spec.ts
src/app/users.service.ts
src/styles.css

Edit duplicate delete popup for application dashboard

edit duplicate delete

---

angular.json
src/app/applications/applications.component.css
src/app/card/card.component.css
src/app/mainproject/mainproject.component.css
src/app/mainproject/mainproject.component.html
src/app/test-express-top-nav/test-express-top-nav.component.css
src/styles.css

I reduced the size of the CSS files. And the budget in angular.json decreased from 7 KB to 6 KB.
I fixed TM 46 and 48 issues for frontend.

The budget is reduced and fixed TM 46 and 48 issues

---

src/app/applications/applications.component.html
src/app/applications/applications.component.ts
src/app/card/card.component.html
src/app/card/card.component.ts
src/app/mainproject/mainproject.component.css
src/app/mainproject/mainproject.component.html
src/styles.css

I fixed the edit functionality validation issue in project and application dashboard.

fixed the edit functionality validation issue

---

src/app/applications/applications.component.html
src/app/applications/applications.component.ts
src/app/mainproject/mainproject.component.html
src/app/mainproject/mainproject.component.ts

The text boxes for name and description are empty after user click the Cancel or Close button in create project and create application.

for empty text boxes

---

package-lock.json
package.json
src/app/applications/applications.component.html
src/app/applications/applications.component.ts
src/app/users.service.ts
src/styles.css

Dropdown search function in application dashboard.

Dropdown search in application dashboard

---

src/app/applications/applications.component.html
src/app/applications/applications.component.ts
src/app/card/card.component.css
src/app/card/card.component.html
src/app/card/card.component.ts
src/app/mainproject/mainproject.component.html
src/app/mainproject/mainproject.component.ts
src/styles.css

I fixed bugs in "TM-50-Description 2 : Create New Project Popup" and "TM-51-Description 5 : Create New Application Popup".

fixed bugs in Create Project and Create Application

---

package-lock.json
package.json
src/app/applications/applications.component.css
src/app/applications/applications.component.html
src/app/applications/applications.component.ts
src/app/card/card.component.css
src/app/users.service.ts
src/styles.css

I have fixed manage member alignment, and functionality of applications and projects dashboard issues.

fix manage member alignment issue.

---

src/app/card/card.component.html
src/app/card/card.component.ts

Updated the search functionality for the project dashboard

---

src/app/card/card.component.html

Sonar issues fixed

---

src/app/applications/applications.component.css
src/app/applications/applications.component.html
src/app/applications/applications.component.ts
src/app/card/card.component.css
src/app/card/card.component.html
src/app/mainproject/mainproject.component.css
src/app/mainproject/mainproject.component.html
src/styles.css

All issues of TM-53 and TM-54 have been resolved.

TM-53 and TM-54 issues are fixed

---

src/app/applications/applications.component.css
src/app/applications/applications.component.html
src/app/card/card.component.css
src/app/card/card.component.html
src/app/card/card.component.ts
src/app/mainproject/mainproject.component.css
src/app/mainproject/mainproject.component.html
src/styles.css

All issues of TM-55 are fixed. And I have updated all the popup windows according to the figma data.

TM-55 issues fixed

---

angular.json
src/app/applications/applications.component.html

TM-56 issues fixed

---

src/app/applications/applications.component.html
src/app/applications/applications.component.ts

There is a bug in Create Application functionality. The user selected Project Name is not taken. I have fixed that issue.

fixed bugs in Create Application

---

src/app/applications/applications.component.css
src/app/applications/applications.component.html
src/app/applications/applications.component.ts
src/app/card/card.component.css
src/app/card/card.component.html
src/assets/bootstrap/css/cardStyles.css
src/styles.css

TM-60 and TM-61 issues are fixed

---

angular.json
src/app/applications/applications.component.html
src/app/applications/applications.component.ts
src/app/card/card.component.html
src/app/card/card.component.ts
src/app/test-express-nav/test-express-nav.component.html

I have fixed the issues for the task menu from the project and application dashboards.
Please review and merge

fixed the issues for the task menu

---

src/app/applications/applications.component.css
src/app/applications/applications.component.html
src/app/applications/applications.component.ts
src/app/mainproject/mainproject.component.ts

fixed TM-72 issues

---

src/app/applications/applications.component.css
src/app/applications/applications.component.html
src/app/applications/applications.component.ts

TM-73 issues are fixed, please review and merge.

TM-73 issues are fixed

---

src/app/applications/applications.component.css
src/app/applications/applications.component.html
src/app/applications/applications.component.ts

TM-74 is updated as per figma.

TM74 issues are fixed
